{% set name = "graphql-server-core" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 04ee90da0322949f7b49ff6905688e3a21a9efbd5a7d7835997e431a0afdbd11

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - graphql-core >=2.3,<3
    - promise >=2.3,<3

test:
  imports:
    - graphql_server

about:
  home: https://graphene-python.org/
  license: MIT
  license_family: MIT
  # requested inclusion of license file in distro https://github.com/graphql-python/graphql-server-core/pull/14
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'This is the core package for using GraphQL in a custom server easily.'
  doc_url: https://docs.graphene-python.org/en/latest/
  dev_url: https://github.com/graphql-python/graphql-server-core

extra:
  recipe-maintainers:
    - carlodri
    - dhirschfeld
    - KingDarBoja
